/*console.log(document.body.firstChild)
console.log(document.body.lastChild)
console.log(document.body.firstElementChild)
console.log(document.body.lastElementChild)
console.log(document.body.childNodes)*/
console.log(document.body.firstChild)
a=document.body.firstChild
console.log(a.parentNode)
console.log(a.parentElement)
console.log(a.firstChild.nextSibling)